### ISSUE TITLE
ELKStackMultiAZinPrivateVPC

### ISSUE THREAD

**Issue by ShadySQL** [guardian/elk-stack#25]
Hi Guys,

Thanks for this! Impressive to say the least. Got a quick one for you. I try now to deploy this stack but receive the following error:

12:58:24 UTC+0200	ROLLBACK_IN_PROGRESS	AWS::CloudFormation::Stack	ELK	The following resource(s) failed to create: [ElkAutoscalingGroup]. . Rollback requested by user.
12:58:23 UTC+0200	CREATE_FAILED	AWS::AutoScaling::AutoScalingGroup	ElkAutoscalingGroup	The availability zones of the specified subnets and the AutoScalingGroup do not match

According to the parameters I give a private subnet and a private subnet on two different AZs. Meaning the private subnet is on EU-WEST-1B and the public subnet is on EU-WEST-1A. 

I read a little about it from Netflix from their asgard project. Is my VPC configuration wrong to launch this ELK template to a none default VPC?

**Comment by satterly** [comment]
The `ELK_Stack_Multi_AZ_in_Private_VPC.json` cloudformation template assumes your VPC is configured as per AWS guidelines which is to have a public and private subnet in each availability zone for the region. See http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Subnets.html

If that isn't the case, then you would need to modify the following lines in the cloudformation template to explicity list the availability zones for the subnets you pass as parameters (or make the list of AZ's a new parameter).

The easiest thing to do would be to delete your existing VPC, if possible, and then use the EC2 instance launch wizard which will create a correctly configured VPC for you...

>  If you use the launch wizard in the Amazon EC2 console to launch a T2 instance type and you do not have any existing VPCs, the wizard creates a nondefault VPC for you, with a subnet in each Availability Zone, an Internet gateway, and a route table that routes all VPC traffic to the Internet gateway. For more information about T2 instance types, see T2 Instances in the Amazon EC2 User Guide for Linux Instances.
