### ISSUE TITLE
Kibana 4 support?

### ISSUE THREAD

**Issue by ajohnstone** [guardian/elk-stack#42]
What is the status of Kibana 4 support? I'm happy to submit a PR for this...

See a branch for kibana4-beta3,

**Comment by satterly** [comment]
Thanks for the offer. Yes a PR would be very welcome. Please create a new cloudformation template for this like in the kibana-beta3 branch. ie. `ELK4_Stack_Multi_AZ_in_Private_VPC.json`.

(Note: We won't every merge the `kibana4-beta3` branch so don't worry about merge conflicts).

**Comment by ajohnstone** [comment]
I mentioned on kibana issue elastic/kibana#354 about integrating the nodejs authentication as a plugin although Kibana does have [shield](http://www.elastic.co/guide/en/shield/current/_shield_with_kibana_4.html), which maybe a conflict of interest.

My interpretation is that the Kibana server will be made more pluggable using hapijs (hopefully).
This may make the need to run a wrapper over kibana unnecessary.

**Comment by ajohnstone** [comment]
@satterly What's your thoughts on using the same cloudformation template and introducing a parameter to control the version? 
E.g.

```
        "KibanaVersion": {
            "Description": "KibanaVersion",
            "Type": "String",
            "Default": "latest",
            "AllowedValues": [
                "latest",
                "kibana-4.0.2-linux-x64"
                "kibana-4.0.2-linux-x86"
            ],
            "ConstraintDescription": "must be a valid kibana version"
        }
    },
    "Conditions": {
        "HasDNS": { "Fn::Not" : [ { "Fn::Equals" : [ { "Ref" : "HostedZoneName" }, "" ] } ] },
        "UseEBS": { "Fn::Not": [ { "Fn::Equals" : [ { "Ref" : "EBSVolumeSize" }, "0" ] } ]},
        "Kibana3": { "Fn::If": [ { "Fn::Equals" : [ { "Ref" : "KibanaVersion" }, "latest" ] } ]}
    },

```

**Comment by satterly** [comment]
If it's as simple as just specifying a version then that would work, I guess. However, I thought Kibana4 involved more fundamental differences due to it having a server-side component. Maybe that changed following beta3. Give it a go and see if it works.

**Comment by satterly** [comment]
Kibana 4 involved many, many changes. See #45
