### ISSUE TITLE
Blank white screen: 

### ISSUE THREAD

**Issue by NickyYo** [guardian/elk-stack#46]
With this http error:

Failed to load resource: the server responded with a status of 503 (Service Unavailable: Back-end server is at capacity)

Any ideas?
Thanks for your hardwork.

**Comment by satterly** [comment]
Looks like the ELB healthcheck was broken. Fixed by f6906af009a0d037aa620a263e1864acd4f41b1d and be3a7945ade3c4608631b20ebae8d056f216d5b8. Can you try again?

**Comment by satterly** [comment]
Testing confirms working for me. Raise another issue if you still have problems.
