### ISSUE TITLE
Blank white screen

### ISSUE THREAD

**Issue by NickyYo** [guardian/elk-stack#47]
Hi Guys,

Just tried it again with the updated script and it's a blank white screen still appears with the following error: 503 (Service Unavailable: Back-end server is at capacity)

I'm using the ElkInstanceType  't2.medium' and the subnets are the same, it shouldn't matter if it wasn't is private right?

**Comment by satterly** [comment]
I haven't tried deploying this will the Public and Private subnets the same. I'll give it a go now.

**Comment by NickyYo** [comment]
Thanks :)

**Comment by satterly** [comment]
Ok. I believe this is now fixed following 1b7c3075bea6a09275c6168d5b7a2b937382a404. Please note that on a `t2.medium` it can take up to 15 minutes to launch the server and for it to be added to the ELB. Until that time you will see a "blank white screen".
