### ISSUE TITLE
Launch issue

### ISSUE THREAD

**Issue by Ezoxu** [guardian/elk-stack#49]
Hi!
Still have problem deploying this...
Created VPC with 1x private, 1x public subnets, 1 gateway.  added subnets for each AZ (2 in my case).
Set up parameters, deployment succeeded. Still getting white screen, error 503. Port 80 seem to be open.
Also LB displays that healthcheck is not passed, vm is outofservice. VM itself is up and running. Used default m4.large... Any advice?

Best regards, Alex.

**Comment by satterly** [comment]
My suggestion would be to change ELB healthcheck to instance status (so that the instances aren't continually being terminated) and login to the instance and troubleshoot from there.

Also, try making any security groups open to the world (just while you are testing) to ensure that they aren't the source of any problems.

**Comment by Ezoxu** [comment]
Actually, i just did log into it, found out that nodejs repo is dead for ubuntu 15, used different one. Also apt-get does not need to have npm package, its included in nodejs. However there are few more issues with logstash connection :)
Also, logcabin, is it something you have created? I could not find any references around....

**Comment by Ezoxu** [comment]
Can we go through a step-by-step procedure of setting it up from scratch if you have time? 
Then we could post a detailed guide how to set it up from beginning to end.
I think other users will like it as well :)

**Comment by satterly** [comment]
Sure -- email me at nfsatterly [at] gmail [dot] com to arrange a time.

**Comment by DPCollins** [comment]
@Ezoxu, not sure if this will help but check the syslog output as logcabin may be throwing a dependency error. If so, perform npm install (with correct permissions) in the /opt/logcabin dir.

**Comment by Ezoxu** [comment]
Hm, logcabin is working fine, right now having logs duplicating :)

**Comment by th3m477** [comment]
Very good script for this - surprised how hard it was to find a Cloud formation template for ELK.

Having the same issue, will do same as above.

**Comment by satterly** [comment]
@th3m477 @Ezoxu If either of you have a fix please report it here or submit a pull request. thanks.

**Comment by gromit6891** [comment]
Any updates on a step-by-step procedure for installation?
I'm getting stuck on a stack build error 'The availability zones of the specified subnets and the AutoScalingGroup do not match'.

**Comment by shaneog** [comment]
I've just set this up with only a minor issue: #52.

@gromit6891 What region did you use? Did you choose all available subnets in this step, or just some?
![2016-01-28 at 11 13](https://cloud.githubusercontent.com/assets/130415/12645299/48fcd9c4-c5b0-11e5-8d09-c9cd4bed7ed3.png)

**Comment by gromit6891** [comment]
@shaneog  I tried us-west-2 and eu-west-1. Using the VPC wizard  two /24 subnets were created, 1 private and 1 public. So, I assumed one for the PrivateVpcSubnets option and one for the PublicVpcSubnets option.

**Comment by satterly** [comment]
This is a limitation of cloudformation and auto-scaling group definitions. See http://stackoverflow.com/a/21442022 and http://stackoverflow.com/a/31404386
