### ISSUE TITLE
eu-west-2 AMI ID?

### ISSUE THREAD

**Issue by takearun** [guardian/elk-stack#79]
Hi,

What would be the ami id used for eu-west-2?

Thanks,
Arun

**Comment by philmcmahon** [comment]
Any recent version of ubuntu should work in theory, maybe this one: ami-aca2b9c8. Or pick from [here](https://cloud-images.ubuntu.com/locator/ec2/) - you want something with HVM instance type

**Comment by satterly** [comment]
@takearun I'll update the CFN template so that the region map works for eu-west-2. Give me a few minutes.

**Comment by takearun** [comment]
Thank you so much guys. Really appreciate your help.

Thanks,
Arun

**Comment by satterly** [comment]
The CFN template has been updated. Give it a go.
